const { NotFoundError, BadRequestError } = require("../../utils/errors.js");
const BaseService = require("../base/base.service.js");
const quoteRepository = require("./quote.repository.js");

const cartRepository = require("../cart/cart.repository.js");
const inventoryRepository = require("../inventory/inventory.repository.js");
const { idGenerate } = require("../../utils/IdGenerator.js");
const { PaymentSchema, QuoteSchema } = require("../../models/index.js");
const { sendMail } = require("../../utils/sendMail.js");
const ImgUploader = require("../../middleware/upload/ImgUploder.js");

class quoteService extends BaseService {
  #repository;
  #cartRepository;
  #inventoryRepository;
  constructor(repository, cartRepository, inventoryRepository, serviceName) {
    super(repository, cartRepository, serviceName);
    this.#repository = repository;
    this.#cartRepository = cartRepository;
    this.#inventoryRepository = inventoryRepository;
  }

  async createquote(payloadFiles, payload, session) {
    // Note: Files are already uploaded in the controller
    // Just pass the payload with prescription URL to repository

    // 2️ Build quote from cart (NO PAYMENT)
    const quote = await this.#repository.createquote(payload, session);

    // 3️ Send admin email
    // await sendMail({
    //   to: process.env.ADMIN_EMAIL,
    //   subject: `New Quote: ${quote.quoteId}`,
    //   html: `<p>Customer: ${quote.customerName}</p>`
    // });

    return quote;
  }

  async createAdminquote(payload, session) {
    const { userRef, quotes, warehouseRef, payment } = payload;
    let paymentResult = null;
    if (payment > 0) {
      const paymentPayload = {
        amount: payment,
        userRef: userRef,
        warehouseRef: warehouseRef,
      };
      paymentResult = await PaymentSchema.create([paymentPayload], { session });
      payload.paymentRef = [paymentResult[0]?._id];
    }

    if (!warehouseRef) throw new NotFoundError("Warehouse is required");

    let productIds = [];
    let totalPrice = 0;
    let subTotalPrice = 0;
    let totalDiscount = 0;
    for (const quote of quotes) {
      const productInfo = await this.#inventoryRepository.findProductInfo(
        quote
      );
      productIds.push({
        productRef: productInfo?.productRef?._id,
        inventoryRef: quote?.inventoryID,
        quantity: quote?.quantity,
        color: productInfo?.name,
        level: productInfo?.level,
        productDiscount: quote?.discount,
      });
      totalPrice += productInfo?.productRef?.mrpPrice * Number(quote?.quantity);
      totalDiscount += Number(quote?.discount) * Number(quote?.quantity) || 0;
      subTotalPrice +=
        productInfo?.productRef?.mrpPrice * Number(quote?.quantity) -
        totalDiscount || 0;

      const availableQuantity = productInfo?.availableQuantity || 0;
      const quantityToHold = Number(quote?.quantity);
      // console.log(
      //   "availableQuantity, quantityToHold",
      //   availableQuantity,
      //   quantityToHold
      // );
      if (availableQuantity < quantityToHold) {
        throw new Error(
          `Insufficient stock for product ${productInfo?.productRef?.name}`
        );
      }
      const inventoryID = quote?.inventoryID;
      const inventoryPayload = {
        availableQuantity: availableQuantity - quantityToHold,
        holdQuantity: Number(productInfo?.holdQuantity) + quantityToHold,
      };
      await this.#inventoryRepository.inventoryQuotePlace(
        inventoryID,
        inventoryPayload,
        session
      );
    }
    payload.products = productIds;
    payload.totalPrice = totalPrice;
    payload.subTotalPrice = subTotalPrice;
    payload.discount = totalDiscount;

    // quoteId will be auto-generated by schema default function

    const quoteData = await this.#repository.create(payload, session);
    if (payment > 0) {
      const updatedPayment = await PaymentSchema.findByIdAndUpdate(
        paymentResult[0]._id,
        { quoteRef: quoteData[0]._id },
        { session, new: true }
      );
    }

    return quoteData;
  }

  async getAllquote() {
    return await this.#repository.findAll(
      {},
      ["products.productRef", "products.inventoryRef"],
      {
        "products.productRef": "productId",
        "products.inventoryRef": "inventoryID",
      }
    );
  }

  async getquoteWithPagination(payload) {
    const quote = await this.#repository.getquoteWithPagination(payload);
    return quote;
  }

  async getSinglequote(id) {
    const quoteData = await this.#repository.findById(id);
    if (!quoteData) throw new NotFoundError("quote Not Find");
    return quoteData;
  }

  async getUserAllquote(id) {
    const isObjectId = /^[a-f\d]{24}$/i.test(id);
    const query = {};
    if (!isObjectId) {
      query.correlationId = id;
    } else {
      query.userRef = id;
    }

    const quoteData = await this.#repository.findAll(query, [
      "products.productRef",
    ]);
    if (!quoteData) throw new NotFoundError("quote Not Find");
    return quoteData;
  }

  async quoteTracking(payload) {
    const { quoteId } = payload;

    const quoteData = await this.#repository.findAll({ quoteId: quoteId });
    if (!quoteData) throw new NotFoundError("quote Not Find");
    return quoteData;
  }

  async updatequote(id, payload) {
    // Update the database with the new data
    const quoteData = await this.#repository.updatequote(id, payload);
    return quoteData;
  }

  async updatequoteStatus(id, status, session) {
    if (!status) throw new NotFoundError("Status is required");
    const quoteData = await this.#repository.findById(id);
    if (!quoteData) throw new NotFoundError("quote not found");
    const updateInventoryStatus =
      await this.#inventoryRepository.updateInventoryStatus(
        status,
        quoteData,
        session
      );

    // ll

    const quote = await this.#repository.updatequoteStatus(id, status, session);

    if (!quote) throw new NotFoundError("quote not found");
    return quote;
  }

  async deletequote(id, session) {
    const quote = await this.#repository.findById(id);
    if (!quote) throw new NotFoundError("quote not found");

    // Allow deletion for all statuses that are not in pending/processing states
    const restrictedStatuses = ["DeliveredPending", "InReview"];
    if (restrictedStatuses.includes(quote.status)) {
      throw new BadRequestError(
        `Quote with status '${quote.status}' cannot be deleted. Please update the status first.`
      );
    }

    // If quote was placed but cancelled or not yet processed, rollback inventory
    if (quote.status === "Cancelled" || quote.status === "QuotePlaced") {
      for (const product of quote.products) {
        const inventoryRef = product.inventoryRef;

        if (!inventoryRef) continue;

        const inventory = await this.#inventoryRepository.findById(
          inventoryRef
        );
        if (!inventory) {
          console.warn(
            `Inventory not found for ID: ${inventoryRef}, skipping rollback`
          );
          continue;
        }

        const inventoryPayload = {
          availableQuantity:
            inventory.availableQuantity + Number(product.quantity),
          holdQuantity: inventory.holdQuantity - Number(product.quantity),
        };

        await this.#inventoryRepository.inventoryQuotePlace(
          inventoryRef,
          inventoryPayload,
          session
        );
      }
    }

    const deletedquote = await this.#repository.deleteById(id, session);
    return deletedquote;
  }
}

module.exports = new quoteService(
  quoteRepository,
  cartRepository,
  inventoryRepository,
  "quote"
);
